---
projection_head_lr: 0.001
min_lr: 0.000001
projection_head_weight_decay: 0.001
T_0: 10000
train_batch_size: 16
val_batch_size: 32
text_model:
  num_embeddings: 50257
  max_seq_length: 30
  embedding_dim: 256

  transformer_encoder:
    num_heads: 8
    dropout_rate: 0.3

  lconv:
    num_heads: 8
    kernel_size: [15, 15, 31, 31, 31, 31, 63, 63, 63, 63, 63, 63]
    padding: "same"
    weight_softmax: True
    bias: False
    dropout_rate: 0.3

  n_blocks: 12
  output_dim: 768
  dropout_rate: 0.3
  lr: 0.00001
  last_layer_norm: False
  pos_encoding_dropout_rate: 0.1

image_model:
  model_name: "mobilenetv3_large"
  alpha: 1.0
  output_dim: 512
  lr: 0.0001

clip_model:
  proj_dim: 512
  tau: 0.9
  dropout_rate: 0.3
